server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name hister-kb.*;

    include /config/nginx/ssl.conf;
    client_max_body_size 0;

    include /config/nginx/authentik-server.conf;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        include /config/nginx/authentik-location.conf;
        set $upstream_app hister;
        set $upstream_port 4433;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
