server {
    listen 443 ssl;
    server_name langfuse.*;

    include /config/nginx/ssl.conf;
    include /config/nginx/proxy.conf;

    location / {
        include /config/nginx/proxy.conf;
        proxy_pass http://langfuse-web:3000;
    }
}
