services:
  dockhand:
    image: fnsys/dockhand@sha256:656ae5ed674d79b8251de275ae4259043f60222bbab563c71ed8dd91edd0b660
    container_name: dockhand
    restart: unless-stopped
    user: "1000:1000"
    group_add:
      - "989"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /opt/appdata/dockhand:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ted/docker:/home/ted/docker
    ports:
      - "127.0.0.1:7777:3000"
    extra_hosts:
      - "auth.helmforge.me:172.20.1.17"
    networks:
      - forge-net
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  forge-net:
    external: true
